#!/bin/bash -e

protoc \
  --plugin=protoc-gen-ts=./node_modules/.bin/protoc-gen-ts \
  -I=$GOPATH/src/github.com/mesg-foundation/core/protobuf/coreapi/ api.proto \
  --js_out=import_style=commonjs,binary:./proto \
  --ts_out=service=true:./proto \